### ISSUE TITLE
Are this project not continued?

### ISSUE THREAD

**Issue by t101804** [LinerSRT/Farlight#2]
Hey i just came to see the project you made.. i wonder it is still continued? i see the offset is outdated tough. are this project also open for contribution?

**Comment by LinerSRT** [comment]
Yes its open, you can create pull requests if you want. Im work on it when i have free time, now im bit busy to continue developing

**Comment by t101804** [comment]
> Yes its open, you can create pull requests if you want. Im work on it when i have free time, now im bit busy to continue developing

do you have discord? what ur username

**Comment by LinerSRT** [comment]
liner_srt
